/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TamanBacaanRouteImport } from './routes/taman-bacaan'
import { Route as StudioPenyalinRouteImport } from './routes/studio-penyalin'
import { Route as PetaKataRouteImport } from './routes/peta-kata'
import { Route as PerpustakaanRouteImport } from './routes/perpustakaan'
import { Route as BukuCeritakuRouteImport } from './routes/buku-ceritaku'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PustakaBookIdRouteImport } from './routes/pustaka.$bookId'
import { Route as BacaBookIdRouteImport } from './routes/baca.$bookId'

const TamanBacaanRoute = TamanBacaanRouteImport.update({
  id: '/taman-bacaan',
  path: '/taman-bacaan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPenyalinRoute = StudioPenyalinRouteImport.update({
  id: '/studio-penyalin',
  path: '/studio-penyalin',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaKataRoute = PetaKataRouteImport.update({
  id: '/peta-kata',
  path: '/peta-kata',
  getParentRoute: () => rootRouteImport,
} as any)
const PerpustakaanRoute = PerpustakaanRouteImport.update({
  id: '/perpustakaan',
  path: '/perpustakaan',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuCeritakuRoute = BukuCeritakuRouteImport.update({
  id: '/buku-ceritaku',
  path: '/buku-ceritaku',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PustakaBookIdRoute = PustakaBookIdRouteImport.update({
  id: '/pustaka/$bookId',
  path: '/pustaka/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BacaBookIdRoute = BacaBookIdRouteImport.update({
  id: '/baca/$bookId',
  path: '/baca/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buku-ceritaku': typeof BukuCeritakuRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/peta-kata': typeof PetaKataRoute
  '/studio-penyalin': typeof StudioPenyalinRoute
  '/taman-bacaan': typeof TamanBacaanRoute
  '/baca/$bookId': typeof BacaBookIdRoute
  '/pustaka/$bookId': typeof PustakaBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buku-ceritaku': typeof BukuCeritakuRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/peta-kata': typeof PetaKataRoute
  '/studio-penyalin': typeof StudioPenyalinRoute
  '/taman-bacaan': typeof TamanBacaanRoute
  '/baca/$bookId': typeof BacaBookIdRoute
  '/pustaka/$bookId': typeof PustakaBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buku-ceritaku': typeof BukuCeritakuRoute
  '/perpustakaan': typeof PerpustakaanRoute
  '/peta-kata': typeof PetaKataRoute
  '/studio-penyalin': typeof StudioPenyalinRoute
  '/taman-bacaan': typeof TamanBacaanRoute
  '/baca/$bookId': typeof BacaBookIdRoute
  '/pustaka/$bookId': typeof PustakaBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buku-ceritaku'
    | '/perpustakaan'
    | '/peta-kata'
    | '/studio-penyalin'
    | '/taman-bacaan'
    | '/baca/$bookId'
    | '/pustaka/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buku-ceritaku'
    | '/perpustakaan'
    | '/peta-kata'
    | '/studio-penyalin'
    | '/taman-bacaan'
    | '/baca/$bookId'
    | '/pustaka/$bookId'
  id:
    | '__root__'
    | '/'
    | '/buku-ceritaku'
    | '/perpustakaan'
    | '/peta-kata'
    | '/studio-penyalin'
    | '/taman-bacaan'
    | '/baca/$bookId'
    | '/pustaka/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BukuCeritakuRoute: typeof BukuCeritakuRoute
  PerpustakaanRoute: typeof PerpustakaanRoute
  PetaKataRoute: typeof PetaKataRoute
  StudioPenyalinRoute: typeof StudioPenyalinRoute
  TamanBacaanRoute: typeof TamanBacaanRoute
  BacaBookIdRoute: typeof BacaBookIdRoute
  PustakaBookIdRoute: typeof PustakaBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taman-bacaan': {
      id: '/taman-bacaan'
      path: '/taman-bacaan'
      fullPath: '/taman-bacaan'
      preLoaderRoute: typeof TamanBacaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-penyalin': {
      id: '/studio-penyalin'
      path: '/studio-penyalin'
      fullPath: '/studio-penyalin'
      preLoaderRoute: typeof StudioPenyalinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta-kata': {
      id: '/peta-kata'
      path: '/peta-kata'
      fullPath: '/peta-kata'
      preLoaderRoute: typeof PetaKataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perpustakaan': {
      id: '/perpustakaan'
      path: '/perpustakaan'
      fullPath: '/perpustakaan'
      preLoaderRoute: typeof PerpustakaanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku-ceritaku': {
      id: '/buku-ceritaku'
      path: '/buku-ceritaku'
      fullPath: '/buku-ceritaku'
      preLoaderRoute: typeof BukuCeritakuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pustaka/$bookId': {
      id: '/pustaka/$bookId'
      path: '/pustaka/$bookId'
      fullPath: '/pustaka/$bookId'
      preLoaderRoute: typeof PustakaBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baca/$bookId': {
      id: '/baca/$bookId'
      path: '/baca/$bookId'
      fullPath: '/baca/$bookId'
      preLoaderRoute: typeof BacaBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BukuCeritakuRoute: BukuCeritakuRoute,
  PerpustakaanRoute: PerpustakaanRoute,
  PetaKataRoute: PetaKataRoute,
  StudioPenyalinRoute: StudioPenyalinRoute,
  TamanBacaanRoute: TamanBacaanRoute,
  BacaBookIdRoute: BacaBookIdRoute,
  PustakaBookIdRoute: PustakaBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
